//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Demographics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Demographics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.Core.Resources.Demographics", typeof(Demographics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Gender_agender {
            get {
                return ResourceManager.GetString("Gender_agender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Gender_bigender {
            get {
                return ResourceManager.GetString("Gender_bigender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49.
        /// </summary>
        internal static string Gender_female {
            get {
                return ResourceManager.GetString("Gender_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Gender_genderfluid {
            get {
                return ResourceManager.GetString("Gender_genderfluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Gender_intersex {
            get {
                return ResourceManager.GetString("Gender_intersex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49.
        /// </summary>
        internal static string Gender_male {
            get {
                return ResourceManager.GetString("Gender_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Orientation_asexual {
            get {
                return ResourceManager.GetString("Orientation_asexual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Orientation_bi {
            get {
                return ResourceManager.GetString("Orientation_bi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Orientation_gay {
            get {
                return ResourceManager.GetString("Orientation_gay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Orientation_pansexual {
            get {
                return ResourceManager.GetString("Orientation_pansexual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 92.
        /// </summary>
        internal static string Orientation_straight {
            get {
                return ResourceManager.GetString("Orientation_straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Orientation_undefined {
            get {
                return ResourceManager.GetString("Orientation_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string Sex_female {
            get {
                return ResourceManager.GetString("Sex_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Sex_intersex {
            get {
                return ResourceManager.GetString("Sex_intersex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49.
        /// </summary>
        internal static string Sex_male {
            get {
                return ResourceManager.GetString("Sex_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Sex_undefined {
            get {
                return ResourceManager.GetString("Sex_undefined", resourceCulture);
            }
        }
    }
}
