//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What? Wait. What? I- I can hear nature talking to me!.
        /// </summary>
        internal static string EnvironmentEventPassedInWrongWay {
            get {
                return ResourceManager.GetString("EnvironmentEventPassedInWrongWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It feels like I&apos;m forgetting something... It&apos;s on the tip of my tongue!.
        /// </summary>
        internal static string FeelsLike {
            get {
                return ResourceManager.GetString("FeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not sure. What should I do? This is confusing!.
        /// </summary>
        internal static string ICantDecide {
            get {
                return ResourceManager.GetString("ICantDecide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know what that means.
        /// </summary>
        internal static string IDontKnow {
            get {
                return ResourceManager.GetString("IDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugh. I have a horrible headache. Don&apos;t talk to me!.
        /// </summary>
        internal static string IHaveAHeadache {
            get {
                return ResourceManager.GetString("IHaveAHeadache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atheists are not tolerated in this world. Sorry!.
        /// </summary>
        internal static string IHaveNoGod {
            get {
                return ResourceManager.GetString("IHaveNoGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t bring a child into this word without giving it a name! Shame on you!.
        /// </summary>
        internal static string IHaveNoName {
            get {
                return ResourceManager.GetString("IHaveNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know, you could at least define me as a Person. Don&apos;t be so lazy!.
        /// </summary>
        internal static string IHaveNoPersonality {
            get {
                return ResourceManager.GetString("IHaveNoPersonality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not sure... let me think... I don&apos;t know..
        /// </summary>
        internal static string LetMeThink {
            get {
                return ResourceManager.GetString("LetMeThink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No! No! Bad voices! I will not do it! I won&apos;t mur- Oh. Hey.... hi..
        /// </summary>
        internal static string MethodCallerInvalid {
            get {
                return ResourceManager.GetString("MethodCallerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t think clearly... my thoughts are all jumbled..
        /// </summary>
        internal static string MyThoughtsAreJumbled {
            get {
                return ResourceManager.GetString("MyThoughtsAreJumbled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know, sometimes, I can hear my body talking to me!.
        /// </summary>
        internal static string PhysicalEventPassedInWrongWay {
            get {
                return ResourceManager.GetString("PhysicalEventPassedInWrongWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have like, special powers. My brain can tell exactly what temperature it is, and I can feel it change. It&apos;s true!.
        /// </summary>
        internal static string TemperatureEventPassedInWrongWay {
            get {
                return ResourceManager.GetString("TemperatureEventPassedInWrongWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woah... I can feel space and time! Trippy!.
        /// </summary>
        internal static string TimeEventPassedInWrongWay {
            get {
                return ResourceManager.GetString("TimeEventPassedInWrongWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s going on? What is this??.
        /// </summary>
        internal static string WhatIsGoingOn {
            get {
                return ResourceManager.GetString("WhatIsGoingOn", resourceCulture);
            }
        }
    }
}
