//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeographicRelationshipDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeographicRelationshipDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.Core.Resources.GeographicRelationshipDescription", typeof(GeographicRelationshipDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east-of.
        /// </summary>
        internal static string EastOf {
            get {
                return ResourceManager.GetString("EastOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includes.
        /// </summary>
        internal static string Includes {
            get {
                return ResourceManager.GetString("Includes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north-east-of.
        /// </summary>
        internal static string NorthEastOf {
            get {
                return ResourceManager.GetString("NorthEastOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north-of.
        /// </summary>
        internal static string NorthOf {
            get {
                return ResourceManager.GetString("NorthOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north-west-of.
        /// </summary>
        internal static string NorthWestOf {
            get {
                return ResourceManager.GetString("NorthWestOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part-of.
        /// </summary>
        internal static string PartOf {
            get {
                return ResourceManager.GetString("PartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south-east-of.
        /// </summary>
        internal static string SouthEastOf {
            get {
                return ResourceManager.GetString("SouthEastOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south-of.
        /// </summary>
        internal static string SouthOf {
            get {
                return ResourceManager.GetString("SouthOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south-west-of.
        /// </summary>
        internal static string SouthWestOf {
            get {
                return ResourceManager.GetString("SouthWestOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west-of.
        /// </summary>
        internal static string WestOf {
            get {
                return ResourceManager.GetString("WestOf", resourceCulture);
            }
        }
    }
}
