//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OccupationalTieReverseDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OccupationalTieReverseDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.Core.Resources.OccupationalTieReverseDescription", typeof(OccupationalTieReverseDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthplace-of.
        /// </summary>
        internal static string BornAt {
            get {
                return ResourceManager.GetString("BornAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conquered-by.
        /// </summary>
        internal static string Conquered {
            get {
                return ResourceManager.GetString("Conquered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destroyed-by.
        /// </summary>
        internal static string Destroyed {
            get {
                return ResourceManager.GetString("Destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deathplace-of.
        /// </summary>
        internal static string DiedAt {
            get {
                return ResourceManager.GetString("DiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fought-against-by.
        /// </summary>
        internal static string FoughtAgainst {
            get {
                return ResourceManager.GetString("FoughtAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fought-for-by.
        /// </summary>
        internal static string FoughtFor {
            get {
                return ResourceManager.GetString("FoughtFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to founded-by.
        /// </summary>
        internal static string Founded {
            get {
                return ResourceManager.GetString("Founded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inaugurated-by.
        /// </summary>
        internal static string Inaugurated {
            get {
                return ResourceManager.GetString("Inaugurated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to led-by.
        /// </summary>
        internal static string Led {
            get {
                return ResourceManager.GetString("Led", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origin-of.
        /// </summary>
        internal static string OriginatedFrom {
            get {
                return ResourceManager.GetString("OriginatedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plundered-by.
        /// </summary>
        internal static string Plundered {
            get {
                return ResourceManager.GetString("Plundered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to razed-by.
        /// </summary>
        internal static string Razed {
            get {
                return ResourceManager.GetString("Razed", resourceCulture);
            }
        }
    }
}
