//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OccurenceReverseDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OccurenceReverseDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.Core.Resources.OccurenceReverseDescription", typeof(OccurenceReverseDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conquered-during.
        /// </summary>
        internal static string Conquest {
            get {
                return ResourceManager.GetString("Conquest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created-during.
        /// </summary>
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destroyed-during.
        /// </summary>
        internal static string Destruction {
            get {
                return ResourceManager.GetString("Destruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ended-during.
        /// </summary>
        internal static string EndedIn {
            get {
                return ResourceManager.GetString("EndedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to happening-of.
        /// </summary>
        internal static string HappenedIn {
            get {
                return ResourceManager.GetString("HappenedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liberated-during.
        /// </summary>
        internal static string Liberation {
            get {
                return ResourceManager.GetString("Liberation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting-of.
        /// </summary>
        internal static string StartedIn {
            get {
                return ResourceManager.GetString("StartedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triggering-of.
        /// </summary>
        internal static string TriggeredBy {
            get {
                return ResourceManager.GetString("TriggeredBy", resourceCulture);
            }
        }
    }
}
