//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.DecisionLeaves.AnswerTextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IDontKnowAnswers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IDontKnowAnswers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.DecisionLeaves.AnswerTextResources.IDontKnowAnswers", typeof(IDontKnowAnswers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t say.
        /// </summary>
        internal static string Icantsay {
            get {
                return ResourceManager.GetString("Icantsay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I {0}don&apos;t know.
        /// </summary>
        internal static string IDontKnow {
            get {
                return ResourceManager.GetString("IDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iunno.
        /// </summary>
        internal static string Iunno {
            get {
                return ResourceManager.GetString("Iunno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve got no {0}clue.
        /// </summary>
        internal static string Noclue {
            get {
                return ResourceManager.GetString("Noclue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I {0}have no idea.
        /// </summary>
        internal static string NoIdea {
            get {
                return ResourceManager.GetString("NoIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a clue{0}.
        /// </summary>
        internal static string Notaclue {
            get {
                return ResourceManager.GetString("Notaclue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0}can&apos;t help{1}.
        /// </summary>
        internal static string Sorrycanthelp {
            get {
                return ResourceManager.GetString("Sorrycanthelp", resourceCulture);
            }
        }
    }
}
