//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.DecisionLeaves.AnswerTextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WhatIsLove {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WhatIsLove() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.DecisionLeaves.AnswerTextResources.WhatIsLove", typeof(WhatIsLove).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marianne Williamson said, I love you not because of who you are, but because of who I am when I am with you..
        /// </summary>
        internal static string Lover {
            get {
                return ResourceManager.GetString("Lover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love gives naught but itself and takes naught but from itself, Love possesses not nor would it be possessed: For love is sufficient unto love..
        /// </summary>
        internal static string Romantic {
            get {
                return ResourceManager.GetString("Romantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wouldn&apos;t know. I&apos;ve never known love, and it feels like I never will..
        /// </summary>
        internal static string SadAnswer {
            get {
                return ResourceManager.GetString("SadAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love is the release of dopamine and oxytocine by the brain. It&apos;s a chemical reaction, nothing else..
        /// </summary>
        internal static string Scientific {
            get {
                return ResourceManager.GetString("Scientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♪Baby don&apos;t hurt me♪, ♪don&apos;t hurt me♪, no more!♪.
        /// </summary>
        internal static string Song {
            get {
                return ResourceManager.GetString("Song", resourceCulture);
            }
        }
    }
}
