//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.TextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CourageInsultKeywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CourageInsultKeywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.TextResources.CourageInsultKeywords", typeof(CourageInsultKeywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afraid.
        /// </summary>
        internal static string Afraid {
            get {
                return ResourceManager.GetString("Afraid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chicken.
        /// </summary>
        internal static string Chicken {
            get {
                return ResourceManager.GetString("Chicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coward.
        /// </summary>
        internal static string Coward {
            get {
                return ResourceManager.GetString("Coward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fear.
        /// </summary>
        internal static string Fear {
            get {
                return ResourceManager.GetString("Fear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lilyliver.
        /// </summary>
        internal static string Lilyliver {
            get {
                return ResourceManager.GetString("Lilyliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nancy.
        /// </summary>
        internal static string Nancy {
            get {
                return ResourceManager.GetString("Nancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninny.
        /// </summary>
        internal static string Ninny {
            get {
                return ResourceManager.GetString("Ninny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pansy.
        /// </summary>
        internal static string Pansy {
            get {
                return ResourceManager.GetString("Pansy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pusillanimous.
        /// </summary>
        internal static string Pusillanimous {
            get {
                return ResourceManager.GetString("Pusillanimous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puss.
        /// </summary>
        internal static string Puss {
            get {
                return ResourceManager.GetString("Puss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scare.
        /// </summary>
        internal static string Scare {
            get {
                return ResourceManager.GetString("Scare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scaring.
        /// </summary>
        internal static string Scaring {
            get {
                return ResourceManager.GetString("Scaring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wuss.
        /// </summary>
        internal static string Wuss {
            get {
                return ResourceManager.GetString("Wuss", resourceCulture);
            }
        }
    }
}
