//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.TextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrudeWords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrudeWords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.TextResources.CrudeWords", typeof(CrudeWords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  anus .
        /// </summary>
        internal static string Anus {
            get {
                return ResourceManager.GetString("Anus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ass.
        /// </summary>
        internal static string Ass {
            get {
                return ResourceManager.GetString("Ass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balls.
        /// </summary>
        internal static string Balls {
            get {
                return ResourceManager.GetString("Balls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boob.
        /// </summary>
        internal static string Boob {
            get {
                return ResourceManager.GetString("Boob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to breast.
        /// </summary>
        internal static string Breast {
            get {
                return ResourceManager.GetString("Breast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butt.
        /// </summary>
        internal static string Butt {
            get {
                return ResourceManager.GetString("Butt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cans .
        /// </summary>
        internal static string Cans {
            get {
                return ResourceManager.GetString("Cans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chest.
        /// </summary>
        internal static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cock.
        /// </summary>
        internal static string Cock {
            get {
                return ResourceManager.GetString("Cock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dick.
        /// </summary>
        internal static string Dick {
            get {
                return ResourceManager.GetString("Dick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuck.
        /// </summary>
        internal static string Fuck {
            get {
                return ResourceManager.GetString("Fuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jugs.
        /// </summary>
        internal static string Jugs {
            get {
                return ResourceManager.GetString("Jugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legs.
        /// </summary>
        internal static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lips.
        /// </summary>
        internal static string Lips {
            get {
                return ResourceManager.GetString("Lips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to masturbate.
        /// </summary>
        internal static string Masturbate {
            get {
                return ResourceManager.GetString("Masturbate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jerk.
        /// </summary>
        internal static string Misc1 {
            get {
                return ResourceManager.GetString("Misc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to penis.
        /// </summary>
        internal static string Penis {
            get {
                return ResourceManager.GetString("Penis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  pound .
        /// </summary>
        internal static string Pound {
            get {
                return ResourceManager.GetString("Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pussy.
        /// </summary>
        internal static string Pussy {
            get {
                return ResourceManager.GetString("Pussy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suck.
        /// </summary>
        internal static string Suck {
            get {
                return ResourceManager.GetString("Suck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tatas.
        /// </summary>
        internal static string Tatas {
            get {
                return ResourceManager.GetString("Tatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testicle.
        /// </summary>
        internal static string Testicle {
            get {
                return ResourceManager.GetString("Testicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vagina.
        /// </summary>
        internal static string Vagina {
            get {
                return ResourceManager.GetString("Vagina", resourceCulture);
            }
        }
    }
}
