//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.TextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmotionalThreatKeywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmotionalThreatKeywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.TextResources.EmotionalThreatKeywords", typeof(EmotionalThreatKeywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hate you.
        /// </summary>
        internal static string Hate {
            get {
                return ResourceManager.GetString("Hate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hurt me.
        /// </summary>
        internal static string Hurt {
            get {
                return ResourceManager.GetString("Hurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hurt myself.
        /// </summary>
        internal static string HurtMyself {
            get {
                return ResourceManager.GetString("HurtMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leave you.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaving you.
        /// </summary>
        internal static string Leaving {
            get {
                return ResourceManager.GetString("Leaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never talking to you.
        /// </summary>
        internal static string NeverTalk {
            get {
                return ResourceManager.GetString("NeverTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t love.
        /// </summary>
        internal static string NoLove {
            get {
                return ResourceManager.GetString("NoLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not talking to you.
        /// </summary>
        internal static string NotTalking {
            get {
                return ResourceManager.GetString("NotTalking", resourceCulture);
            }
        }
    }
}
