//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.TextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FamilyInsultKeywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FamilyInsultKeywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.TextResources.FamilyInsultKeywords", typeof(FamilyInsultKeywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aunt.
        /// </summary>
        internal static string Aunt {
            get {
                return ResourceManager.GetString("Aunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  bro .
        /// </summary>
        internal static string Bro {
            get {
                return ResourceManager.GetString("Bro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brother.
        /// </summary>
        internal static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cousin.
        /// </summary>
        internal static string Cousin {
            get {
                return ResourceManager.GetString("Cousin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  da .
        /// </summary>
        internal static string Da {
            get {
                return ResourceManager.GetString("Da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dad .
        /// </summary>
        internal static string Dad {
            get {
                return ResourceManager.GetString("Dad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dada .
        /// </summary>
        internal static string dada {
            get {
                return ResourceManager.GetString("dada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daddy.
        /// </summary>
        internal static string Daddy {
            get {
                return ResourceManager.GetString("Daddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daughter.
        /// </summary>
        internal static string Daughter {
            get {
                return ResourceManager.GetString("Daughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to father.
        /// </summary>
        internal static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to granda.
        /// </summary>
        internal static string Granda {
            get {
                return ResourceManager.GetString("Granda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandad.
        /// </summary>
        internal static string Granddad {
            get {
                return ResourceManager.GetString("Granddad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandma.
        /// </summary>
        internal static string Grandma {
            get {
                return ResourceManager.GetString("Grandma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandpa.
        /// </summary>
        internal static string Grandpa {
            get {
                return ResourceManager.GetString("Grandpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbred.
        /// </summary>
        internal static string Inbred {
            get {
                return ResourceManager.GetString("Inbred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ma .
        /// </summary>
        internal static string Ma {
            get {
                return ResourceManager.GetString("Ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mama .
        /// </summary>
        internal static string Mama {
            get {
                return ResourceManager.GetString("Mama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mom .
        /// </summary>
        internal static string Mom {
            get {
                return ResourceManager.GetString("Mom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mommy.
        /// </summary>
        internal static string Mommy {
            get {
                return ResourceManager.GetString("Mommy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mother.
        /// </summary>
        internal static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mum .
        /// </summary>
        internal static string Mum {
            get {
                return ResourceManager.GetString("Mum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mummy.
        /// </summary>
        internal static string Mummy {
            get {
                return ResourceManager.GetString("Mummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  nana .
        /// </summary>
        internal static string Nana {
            get {
                return ResourceManager.GetString("Nana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nephew.
        /// </summary>
        internal static string Nephew {
            get {
                return ResourceManager.GetString("Nephew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to niece.
        /// </summary>
        internal static string Niece {
            get {
                return ResourceManager.GetString("Niece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sis .
        /// </summary>
        internal static string Sis {
            get {
                return ResourceManager.GetString("Sis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  son .
        /// </summary>
        internal static string Son {
            get {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uncle.
        /// </summary>
        internal static string Uncle {
            get {
                return ResourceManager.GetString("Uncle", resourceCulture);
            }
        }
    }
}
