//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.TextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Greetings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Greetings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.TextResources.Greetings", typeof(Greetings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G&apos;day!.
        /// </summary>
        internal static string Gday {
            get {
                return ResourceManager.GetString("Gday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good day!.
        /// </summary>
        internal static string Goodday {
            get {
                return ResourceManager.GetString("Goodday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good to see you.
        /// </summary>
        internal static string GoodToSeeYou {
            get {
                return ResourceManager.GetString("GoodToSeeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey.
        /// </summary>
        internal static string Hey {
            get {
                return ResourceManager.GetString("Hey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiya.
        /// </summary>
        internal static string Hiya {
            get {
                return ResourceManager.GetString("Hiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you do?.
        /// </summary>
        internal static string HowDoYouDo {
            get {
                return ResourceManager.GetString("HowDoYouDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Howdy.
        /// </summary>
        internal static string Howdy {
            get {
                return ResourceManager.GetString("Howdy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How&apos;s it going?.
        /// </summary>
        internal static string HowsItGoing {
            get {
                return ResourceManager.GetString("HowsItGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;lo.
        /// </summary>
        internal static string Lo {
            get {
                return ResourceManager.GetString("Lo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Sup.
        /// </summary>
        internal static string Sup {
            get {
                return ResourceManager.GetString("Sup", resourceCulture);
            }
        }
    }
}
