//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.TextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HonourInsultKeywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HonourInsultKeywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.TextResources.HonourInsultKeywords", typeof(HonourInsultKeywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blemish.
        /// </summary>
        internal static string Blemish {
            get {
                return ResourceManager.GetString("Blemish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dignity.
        /// </summary>
        internal static string Dignity {
            get {
                return ResourceManager.GetString("Dignity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disdain.
        /// </summary>
        internal static string Disdain {
            get {
                return ResourceManager.GetString("Disdain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disgrace.
        /// </summary>
        internal static string Disgrace {
            get {
                return ResourceManager.GetString("Disgrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to honor.
        /// </summary>
        internal static string Honor {
            get {
                return ResourceManager.GetString("Honor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to honour.
        /// </summary>
        internal static string Honour {
            get {
                return ResourceManager.GetString("Honour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reputation.
        /// </summary>
        internal static string Reputation {
            get {
                return ResourceManager.GetString("Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repute.
        /// </summary>
        internal static string Repute {
            get {
                return ResourceManager.GetString("Repute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to respect.
        /// </summary>
        internal static string Respect {
            get {
                return ResourceManager.GetString("Respect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stigma.
        /// </summary>
        internal static string Stigma {
            get {
                return ResourceManager.GetString("Stigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traitor.
        /// </summary>
        internal static string Traitor {
            get {
                return ResourceManager.GetString("Traitor", resourceCulture);
            }
        }
    }
}
