//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.TextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IntelligenceInsultKeywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntelligenceInsultKeywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.TextResources.IntelligenceInsultKeywords", typeof(IntelligenceInsultKeywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brain.
        /// </summary>
        public static string brain {
            get {
                return ResourceManager.GetString("brain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dim.
        /// </summary>
        public static string dim {
            get {
                return ResourceManager.GetString("dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dumb.
        /// </summary>
        public static string dumb {
            get {
                return ResourceManager.GetString("dumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idiot.
        /// </summary>
        public static string idiot {
            get {
                return ResourceManager.GetString("idiot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imbecile.
        /// </summary>
        public static string imbecile {
            get {
                return ResourceManager.GetString("imbecile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intelligent.
        /// </summary>
        public static string intelligent {
            get {
                return ResourceManager.GetString("intelligent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moron.
        /// </summary>
        public static string moron {
            get {
                return ResourceManager.GetString("moron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numbnuts.
        /// </summary>
        public static string numbnuts {
            get {
                return ResourceManager.GetString("numbnuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numbskull.
        /// </summary>
        public static string numbskull {
            get {
                return ResourceManager.GetString("numbskull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to senile.
        /// </summary>
        public static string Senile {
            get {
                return ResourceManager.GetString("Senile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smart.
        /// </summary>
        public static string smart {
            get {
                return ResourceManager.GetString("smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stupid.
        /// </summary>
        public static string stupid {
            get {
                return ResourceManager.GetString("stupid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wit.
        /// </summary>
        public static string wit {
            get {
                return ResourceManager.GetString("wit", resourceCulture);
            }
        }
    }
}
