//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.TextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PhysicalThreatKeywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PhysicalThreatKeywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.TextResources.PhysicalThreatKeywords", typeof(PhysicalThreatKeywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  crush .
        /// </summary>
        internal static string Crush {
            get {
                return ResourceManager.GetString("Crush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crushing.
        /// </summary>
        internal static string Crushing {
            get {
                return ResourceManager.GetString("Crushing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cut .
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cutting.
        /// </summary>
        internal static string Cutting {
            get {
                return ResourceManager.GetString("Cutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gun.
        /// </summary>
        internal static string Gun {
            get {
                return ResourceManager.GetString("Gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hurt you.
        /// </summary>
        internal static string Hurt {
            get {
                return ResourceManager.GetString("Hurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hurting you.
        /// </summary>
        internal static string HurtingYou {
            get {
                return ResourceManager.GetString("HurtingYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  kick .
        /// </summary>
        internal static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kicking.
        /// </summary>
        internal static string Kicking {
            get {
                return ResourceManager.GetString("Kicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kill you.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to killing you.
        /// </summary>
        internal static string KillingYou {
            get {
                return ResourceManager.GetString("KillingYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knife.
        /// </summary>
        internal static string Knife {
            get {
                return ResourceManager.GetString("Knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  maim .
        /// </summary>
        internal static string Maim {
            get {
                return ResourceManager.GetString("Maim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maiming.
        /// </summary>
        internal static string Maiming {
            get {
                return ResourceManager.GetString("Maiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to punch.
        /// </summary>
        internal static string Punch {
            get {
                return ResourceManager.GetString("Punch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rip you.
        /// </summary>
        internal static string Rip {
            get {
                return ResourceManager.GetString("Rip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ripping.
        /// </summary>
        internal static string Ripping {
            get {
                return ResourceManager.GetString("Ripping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  slap .
        /// </summary>
        internal static string Slap {
            get {
                return ResourceManager.GetString("Slap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slapping.
        /// </summary>
        internal static string Slapping {
            get {
                return ResourceManager.GetString("Slapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  smash.
        /// </summary>
        internal static string Smash {
            get {
                return ResourceManager.GetString("Smash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stab you.
        /// </summary>
        internal static string Stab {
            get {
                return ResourceManager.GetString("Stab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stabbing.
        /// </summary>
        internal static string Stabbing {
            get {
                return ResourceManager.GetString("Stabbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  tear .
        /// </summary>
        internal static string Tear {
            get {
                return ResourceManager.GetString("Tear", resourceCulture);
            }
        }
    }
}
