//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNPC.API.TextResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrengthInsultKeywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrengthInsultKeywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RNPC.TextResources.StrengthInsultKeywords", typeof(StrengthInsultKeywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delicate.
        /// </summary>
        internal static string Delicate {
            get {
                return ResourceManager.GetString("Delicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feeble.
        /// </summary>
        internal static string Feeble {
            get {
                return ResourceManager.GetString("Feeble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flaccid.
        /// </summary>
        internal static string Flaccid {
            get {
                return ResourceManager.GetString("Flaccid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fragile.
        /// </summary>
        internal static string Fragile {
            get {
                return ResourceManager.GetString("Fragile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frail.
        /// </summary>
        internal static string Frail {
            get {
                return ResourceManager.GetString("Frail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limp.
        /// </summary>
        internal static string Limp {
            get {
                return ResourceManager.GetString("Limp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puny.
        /// </summary>
        internal static string Puny {
            get {
                return ResourceManager.GetString("Puny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sick.
        /// </summary>
        internal static string Sick {
            get {
                return ResourceManager.GetString("Sick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weak.
        /// </summary>
        internal static string Weak {
            get {
                return ResourceManager.GetString("Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wuss.
        /// </summary>
        internal static string Wuss {
            get {
                return ResourceManager.GetString("Wuss", resourceCulture);
            }
        }
    }
}
